services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db-local'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'eranyacloud'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'j4ng4nd1sh4r3'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'rootbukanakar'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./db:/var/lib/mysql